name: Build PR Check

on:
  pull_request:
    branches:
      - master

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build-pr:
    name: Build PR Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build PR
        run: docker build . --file Dockerfile --tag jessvv/music-bot:pr_$PR_NUMBER
      - name: Docker Push PR
        run: docker push jessvv/music-bot:pr_$PR_NUMBER
